### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
**Description:**

Minor proofreading improvement (punctuation, syntax structure, semantics, grammar, typo correction).

Thanks to @shindarth for making me believe there are still a lot of good people out there. Arrivederci! 😄

**Ticket closure or reference:**

No issues available to reference or close.

#sign-off

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
- [X] **Rich diff view:** https://github.com/FrancescoBorzi/why-I-hate-wow-private-servers/pull/18/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 (for easier review)

**Comment by FrancescoBorzi** [comment]
many thanks @illfated ! your help is always welcome

**Comment by FrancescoBorzi** [comment]
@illfated are you on Discord? I'd like to talk to you

**Comment by ghost** [comment]
I have got the app, which channel/repo would you like for me to join?

**Comment by FrancescoBorzi** [comment]
https://discordapp.com/invite/gkt4y2x

**Pull request merged**
