### PR TITLE
Translate to Russian language

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
- Translate text to ruRU

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
@Helias thanks

**Comment by Winfidonarleyan** [comment]
infinity fixes are not the limit :D

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan spasibo. Is this still WIP or ready to be merged?

I've solved the merge conflicts

**Comment by Winfidonarleyan** [comment]
Is wip, i say if done

**Comment by Winfidonarleyan** [comment]
Okay, go merge @FrancescoBorzi

**Comment by Viste** [comment]
:((( Очень плохо Андрей очень плохо :((

**Comment by Winfidonarleyan** [comment]
Okay, need wait

**Comment by FrancescoBorzi** [comment]
ok waiting for you ;)

thanks a lot @Winfidonarleyan @Viste

**Comment by Winfidonarleyan** [comment]
@Viste re-check and go merge maybe?

**Comment by Viste** [comment]
ready

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan @Viste thank you!

**Pull request merged**
