### PR TITLE
credit/authors: Link order correction

### PR DESCRIPTION
**Pull request by ghost**
Match the authors' links to their text descriptions
- MaNGOS
- TrinityCore

Whitespace change:
- remove redundant blank line at EOF

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
hey @illfated  how are you?? thanks for your contribution

**Comment by ghost** [comment]
You are welcome. Happy to see that you are still hanging around. I agree with your sentiments in the document (I read it via Google Translate).

How are you? I suppose I am doing OK, working as a general IT support & technician for a small business in Oslo, Norway. Most of my days consist of being available to support the attorneys and solicitors (training to become attorneys-at-law), as well as the small group of admin people. At the moment, our website is closed for maintenance, but it should be up again tomorrow. (https://scolaw.no)

**Comment by FrancescoBorzi** [comment]
@illfated I'm also happy to see you around! I will definitely publish an English version.

I'm doing pretty good too, working as programmer as always!

**Comment by FrancescoBorzi** [comment]
@illfated you should visit us on our Discord! https://discord.com/invite/gkt4y2x

**Pull request merged**
